DROP TABLE IF EXISTS utility_billing;
CREATE TABLE utility_billing (
    id                  SERIAL PRIMARY KEY,
    hydro_gas_id        BIGINT,
    account_number      BIGINT,
    customer_name       TEXT,
    ssc_number          TEXT,
    customer_information TEXT,
    service_address     TEXT,
    town                TEXT,
    meter_number        TEXT,
    actual_service_type TEXT,
    rate                TEXT,
    service_from_date   TIMESTAMP,
    service_to_date     TIMESTAMP,
    current_reading     NUMERIC,
    days_of_service     INTEGER,
    billing_units       NUMERIC,
    read_code           TEXT,
    basic_charge        NUMERIC,
    primary_other       NUMERIC,
    supplemental        NUMERIC,
    transportation      NUMERIC,
    distribution        NUMERIC,
    frp_refund          NUMERIC,
    city_tax            NUMERIC,
    gst_on_city_tax     NUMERIC,
    carbon_charge       NUMERIC,
    pst                 NUMERIC,
    gst                 NUMERIC,
    adjustment          NUMERIC,
    amount_due          NUMERIC,
    demand_billing      NUMERIC,
    billed_kva          NUMERIC,
    measured_demand     NUMERIC,
    high_demand         NUMERIC,
    contract_demand     NUMERIC,
    multiplier          NUMERIC,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);
